[package]
name = "leifstout/servicePlayerData"
description = "Non-persistent service player data"
version = "0.1.0"
license = "MIT"
authors = ["Leif Stout <leifstout@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml", "LICENSE"]

[dependencies]
Signal = "sleitnick/signal@2.0.0"
Sift = "csqrl/sift@0.0.11"